substitutions:
  devicename: ESP Heater 4
  lower_devicename: esp-heater-4

globals:
  id: socket_power
  type: float
  initial_value: "1200"

external_components:
  - source:
      type: local
      path: components

esphome:
  name: "${lower_devicename}"
  platform: ESP8266
  board: esp01_1m
  includes:
    - mill.h

# Enable logging
logger:
  baud_rate: 0
  level: VERBOSE

api:
  encryption:
    key: "9DfUkpTV/6+PinUfizUiEjYVOWfXJVQWXcx5kLG+qrU="

ota:
  password: "ccff5da6ad59625e8cfc00518abb0f0e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: "0s"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${lower_devicename} Fallback Hotspot"
    password: "uiCKDXWtynbO"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

uart:
  id: uart1
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600


mill_convection:
  uart_id: uart1